-- Создаем схему DM для хранения витрин данных
CREATE SCHEMA IF NOT EXISTS DM;

-- Витрина оборотов
DROP TABLE IF EXISTS DM.DM_ACCOUNT_TURNOVER_F;
CREATE TABLE DM.DM_ACCOUNT_TURNOVER_F (
    ON_DATE DATE NOT NULL,
    ACCOUNT_RK NUMERIC NOT NULL,
    CREDIT_AMOUNT NUMERIC(23,8),
    CREDIT_AMOUNT_RUB NUMERIC(23,8),
    DEBET_AMOUNT NUMERIC(23,8),
    DEBET_AMOUNT_RUB NUMERIC(23,8),
    CONSTRAINT PK_DM_ACCOUNT_TURNOVER_F PRIMARY KEY (ON_DATE, ACCOUNT_RK)
);

-- Витрина остатков
DROP TABLE IF EXISTS DM.DM_ACCOUNT_BALANCE_F;
CREATE TABLE DM.DM_ACCOUNT_BALANCE_F (
    ON_DATE DATE NOT NULL,
    ACCOUNT_RK NUMERIC NOT NULL,
    BALANCE_OUT NUMERIC(23,8),
    BALANCE_OUT_RUB NUMERIC(23,8),
    CONSTRAINT PK_DM_ACCOUNT_BALANCE_F PRIMARY KEY (ON_DATE, ACCOUNT_RK)
);

-- Проверка создания таблиц
SELECT schemaname, tablename FROM pg_tables WHERE schemaname = 'dm' ORDER BY tablename;