-- Процедура расчёта витрины оборотов DM.DM_ACCOUNT_TURNOVER_F

CREATE OR REPLACE PROCEDURE DS.FILL_ACCOUNT_TURNOVER_F(
    i_OnDate DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM DM.DM_ACCOUNT_TURNOVER_F WHERE ON_DATE = i_OnDate;
    
    -- Кредитовые обороты
    INSERT INTO DM.DM_ACCOUNT_TURNOVER_F (ON_DATE, ACCOUNT_RK, CREDIT_AMOUNT, CREDIT_AMOUNT_RUB)
    SELECT 
        i_OnDate,
        CREDIT_ACCOUNT_RK,
        ROUND(SUM(CREDIT_AMOUNT)::NUMERIC, 2),
        ROUND(SUM(CREDIT_AMOUNT)::NUMERIC, 2)
    FROM DS.FT_POSTING_F
    WHERE OPER_DATE = i_OnDate
      AND CREDIT_AMOUNT IS NOT NULL
      AND CREDIT_AMOUNT != 0
    GROUP BY CREDIT_ACCOUNT_RK;
    
    -- Дебетовые обороты
    INSERT INTO DM.DM_ACCOUNT_TURNOVER_F (ON_DATE, ACCOUNT_RK, DEBET_AMOUNT, DEBET_AMOUNT_RUB)
    SELECT 
        i_OnDate,
        DEBET_ACCOUNT_RK,
        ROUND(SUM(DEBET_AMOUNT)::NUMERIC, 2),
        ROUND(SUM(DEBET_AMOUNT)::NUMERIC, 2)
    FROM DS.FT_POSTING_F
    WHERE OPER_DATE = i_OnDate
      AND DEBET_AMOUNT IS NOT NULL
      AND DEBET_AMOUNT != 0
    GROUP BY DEBET_ACCOUNT_RK
    ON CONFLICT (ON_DATE, ACCOUNT_RK) DO UPDATE SET
        DEBET_AMOUNT = EXCLUDED.DEBET_AMOUNT,
        DEBET_AMOUNT_RUB = EXCLUDED.DEBET_AMOUNT_RUB;
    
    -- Логирование
    INSERT INTO LOGS.ETL_LOG (TABLE_NAME, OPERATION_TYPE, START_TIME, END_TIME, ROWS_AFFECTED, STATUS)
    VALUES ('DM.DM_ACCOUNT_TURNOVER_F', 'TURNOVER_LOAD', NOW(), NOW(), 
            (SELECT COUNT(*) FROM DM.DM_ACCOUNT_TURNOVER_F WHERE ON_DATE = i_OnDate), 
            'SUCCESS');
    
    RAISE NOTICE 'Обороты за %: % записей', i_OnDate, 
                 (SELECT COUNT(*) FROM DM.DM_ACCOUNT_TURNOVER_F WHERE ON_DATE = i_OnDate);
END;
$$;