-- Задание 1.3: Создание витрины для формы 101

CREATE SCHEMA IF NOT EXISTS DM;

DROP TABLE IF EXISTS DM.DM_F101_ROUND_F;

CREATE TABLE DM.DM_F101_ROUND_F (
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    CHAPTER CHAR(1),
    LEDGER_ACCOUNT CHAR(5),
    CHARACTERISTIC CHAR(1),
    BALANCE_IN_RUB NUMERIC(30,8),
    BALANCE_IN_VAL NUMERIC(30,8),
    BALANCE_IN_TOTAL NUMERIC(30,8),
    TURN_DEB_RUB NUMERIC(30,8),
    TURN_DEB_VAL NUMERIC(30,8),
    TURN_DEB_TOTAL NUMERIC(30,8),
    TURN_CRE_RUB NUMERIC(30,8),
    TURN_CRE_VAL NUMERIC(30,8),
    TURN_CRE_TOTAL NUMERIC(30,8),
    BALANCE_OUT_RUB NUMERIC(30,8),
    BALANCE_OUT_VAL NUMERIC(30,8),
    BALANCE_OUT_TOTAL NUMERIC(30,8),
    CONSTRAINT PK_DM_F101_ROUND_F PRIMARY KEY (FROM_DATE, TO_DATE, CHAPTER, LEDGER_ACCOUNT)
);

-- Проверка создания таблицы
SELECT schemaname, tablename FROM pg_tables WHERE tablename = 'dm_f101_round_f';