-- Создание схем
CREATE SCHEMA IF NOT EXISTS DS;
CREATE SCHEMA IF NOT EXISTS LOGS;


-- Таблица DS.FT_BALANCE_F (остатки)
CREATE TABLE IF NOT EXISTS DS.FT_BALANCE_F (
    ON_DATE DATE NOT NULL,
    ACCOUNT_RK NUMERIC NOT NULL,
    CURRENCY_RK NUMERIC,
    BALANCE_OUT FLOAT,
    CONSTRAINT PK_FT_BALANCE_F PRIMARY KEY (ON_DATE, ACCOUNT_RK)
);


-- Таблица DS.FT_POSTING_F (проводки) - без PK
CREATE TABLE IF NOT EXISTS DS.FT_POSTING_F (
    OPER_DATE DATE NOT NULL,
    CREDIT_ACCOUNT_RK NUMERIC NOT NULL,
    DEBET_ACCOUNT_RK NUMERIC NOT NULL,
    CREDIT_AMOUNT FLOAT,
    DEBET_AMOUNT FLOAT
);


-- Таблица DS.MD_ACCOUNT_D (счета)
CREATE TABLE IF NOT EXISTS DS.MD_ACCOUNT_D (
    DATA_ACTUAL_DATE DATE NOT NULL,
    DATA_ACTUAL_END_DATE DATE NOT NULL,
    ACCOUNT_RK NUMERIC NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    CHAR_TYPE VARCHAR(1) NOT NULL,
    CURRENCY_RK NUMERIC NOT NULL,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    CONSTRAINT PK_MD_ACCOUNT_D PRIMARY KEY (DATA_ACTUAL_DATE, ACCOUNT_RK)
);


-- Таблица DS.MD_CURRENCY_D (валюты)
CREATE TABLE IF NOT EXISTS DS.MD_CURRENCY_D (
    CURRENCY_RK NUMERIC NOT NULL,
    DATA_ACTUAL_DATE DATE NOT NULL,
    DATA_ACTUAL_END_DATE DATE,
    CURRENCY_CODE VARCHAR(3),
    CODE_ISO_CHAR VARCHAR(3),
    CONSTRAINT PK_MD_CURRENCY_D PRIMARY KEY (CURRENCY_RK, DATA_ACTUAL_DATE)
);


-- Таблица DS.MD_EXCHANGE_RATE_D (курсы валют)
CREATE TABLE IF NOT EXISTS DS.MD_EXCHANGE_RATE_D (
    DATA_ACTUAL_DATE DATE NOT NULL,
    DATA_ACTUAL_END_DATE DATE,
    CURRENCY_RK NUMERIC NOT NULL,
    REDUCED_COURCE FLOAT,
    CODE_ISO_NUM VARCHAR(3),
    CONSTRAINT PK_MD_EXCHANGE_RATE_D PRIMARY KEY (DATA_ACTUAL_DATE, CURRENCY_RK)
);


-- Таблица DS.MD_LEDGER_ACCOUNT_S (балансовые счета)
-- Удаляем старую таблицу
DROP TABLE IF EXISTS DS.MD_LEDGER_ACCOUNT_S;

-- Создаём новую только с колонками из CSV
CREATE TABLE IF NOT EXISTS DS.MD_LEDGER_ACCOUNT_S (
    CHAPTER CHAR(1),
    CHAPTER_NAME VARCHAR(16),
    SECTION_NUMBER INTEGER,
    SECTION_NAME VARCHAR(22),
    SUBSECTION_NAME VARCHAR(21),
    LEDGER1_ACCOUNT INTEGER,
    LEDGER1_ACCOUNT_NAME VARCHAR(47),
    LEDGER_ACCOUNT INTEGER NOT NULL,
    LEDGER_ACCOUNT_NAME VARCHAR(153),
    CHARACTERISTIC CHAR(1),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    CONSTRAINT PK_MD_LEDGER_ACCOUNT_S PRIMARY KEY (LEDGER_ACCOUNT, START_DATE)
);


-- Таблица логов LOGS.ETL_LOG
CREATE TABLE IF NOT EXISTS LOGS.ETL_LOG (
    LOG_ID SERIAL PRIMARY KEY,
    TABLE_NAME VARCHAR(50),
    OPERATION_TYPE VARCHAR(20),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    ROWS_AFFECTED INTEGER,
    STATUS VARCHAR(20),
    ERROR_MESSAGE TEXT
);


CREATE DATABASE bank_db;

SELECT COUNT(*) FROM DS.FT_BALANCE_F;
SELECT COUNT(*) FROM DS.FT_POSTING_F;
SELECT COUNT(*) FROM LOGS.ETL_LOG;

-- Столкнулся с проблемой, что данные в колонках CURRENCY_CODE и CODE_ISO_CHAR длиннее 3 символов, устраняю путем увеличения размера колонок
ALTER TABLE DS.MD_CURRENCY_D ALTER COLUMN CURRENCY_CODE TYPE VARCHAR(10);
ALTER TABLE DS.MD_CURRENCY_D ALTER COLUMN CODE_ISO_CHAR TYPE VARCHAR(10);
-- Запасная мера после ошибок с загрузкой. TRUNCATE очищает таблицу, чтобы при повторной загрузке не было конфликта с уже частично загруженными данными
TRUNCATE TABLE DS.MD_CURRENCY_D;

-- 1. Проверка всех таблиц
SELECT 'FT_BALANCE_F' as table_name, COUNT(*) as rows FROM DS.FT_BALANCE_F
UNION ALL SELECT 'FT_POSTING_F', COUNT(*) FROM DS.FT_POSTING_F
UNION ALL SELECT 'MD_ACCOUNT_D', COUNT(*) FROM DS.MD_ACCOUNT_D
UNION ALL SELECT 'MD_CURRENCY_D', COUNT(*) FROM DS.MD_CURRENCY_D
UNION ALL SELECT 'MD_EXCHANGE_RATE_D', COUNT(*) FROM DS.MD_EXCHANGE_RATE_D
UNION ALL SELECT 'MD_LEDGER_ACCOUNT_S', COUNT(*) FROM DS.MD_LEDGER_ACCOUNT_S
ORDER BY table_name;

-- 2. Просмотр логов ETL
SELECT * FROM LOGS.ETL_LOG ORDER BY LOG_ID DESC;

-- 3. Пример данных из FT_BALANCE_F
SELECT * FROM DS.FT_BALANCE_F LIMIT 10;

-- 4. Пример данных из FT_POSTING_F
SELECT * FROM DS.FT_POSTING_F LIMIT 10;